on:
  push:
    branches:
      - main

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
    # checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # install the latest version of Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    # initialize a new or existing Terraform working directory by creating initial files, downloading remote state files and working with plugin modules
    - name: Terraform Init
      id: init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive

    # validate terraform files
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
